name: Oh_the_dungeons_youll_go
authors: [shadow_wind]
main: otd.Main
load: startup
api-version: 1.14
version: 14.1
softdepend: [WorldEdit]
commands:
  oh_the_dungeons:
    aliases: [otd]
    description: Open the OTD world manager
    usage: /<command>
  oh_the_dungeons_place:
    aliases: [otd_place]
    description: Place a dungeon at your current location
    usage: /<command> type
  oh_the_dungeons_cp:
    aliases: [otd_cp]
    description: Copy world config
    usage: /<command> source dest
  oh_the_dungeons_tp:
    aliases: [otd_tp]
    description: open the dungeon plot teleport GUI
    usage: /<command>
permissions:
  oh_the_dungeons.admin:
    default: op
    description: open the inventory GUI
  oh_the_dungeons.teleport:
    default: true
    description: open the dungeon plot teleport GUI
